clear; close all; clc;

addpath('./helpers');

Fs = 44100;
duration = 2;
F0 = [27.5,440, 1046.5, 4081];


    fontName = 'Times';
    fontSize = 10;

% Specify wavetables, either...
% a single trivial wavetable:
wavetables = "square";
% an array of trivial wavetables:
% wavetables = ["sawtooth", "noise", "square", "sine", "sineBroken"];
% an audio file to read and split into wavetable chunks.
% wavetables = audioread('./wavetables/braids2.wav');

%IntTypes = {'truncate','linear','cubic','sinc'};
WtLenght = [2^8,2^9,2^10,2^11,2^12];

for i=1:4
for n=1:5

testTable = wavetable(Fs, duration, F0(i), ...
    'Wavetables', wavetables, ...
    'WavetableLength', WtLenght(n), ...
    'InterpolationType', 'cubic', ...
    'Oversample', 1, ...
    'MipmapsPerOctave', 1, ...
    'OutputAmplitude', 1 ...
);


        SNR(n,i) = snr(testTable, Fs, round(Fs*n/2/F0(i))) 
        pitchEstimates(n,i) = mean(pitch(testTable, Fs, 'Range', [50, 5000], 'Method', 'LHS'));
        specCentroids(n,i) = mean(spectralCentroid(testTable,Fs));
        rmsValues(n,i) = rms(testTable);
end 
end
%%

for n=1:4

y(:,n) = wavetable(Fs, duration, F0(2), ...
    'Wavetables', wavetables, ...
    'WavetableLength', WtLenght(n), ...
    'InterpolationType', 'cubic', ...
    'Oversample', 1, ...
    'MipmapsPerOctave', 1, ...
    'OutputAmplitude', 1 ...
);

    X(:,n) = abs(fft(y(:,n), Fs));
   X(:,n) = db(X(:,n)/max(X(:,n)));

           %get values of test wavetables


end 


figure
subplot(4,1,1)
plot(linspace(0, Fs-1, Fs), X(:,1), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
        SNRstr = sprintf('SNR: %.1f',SNR(1,i));
        legend(SNRstr)
        grid on;
subtitle('Drop zero, 440 Hz')
subplot(4,1,2)
plot(linspace(0, Fs-1, Fs), X(:,2), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
        SNRstr = sprintf('SNR: %.1f',SNR(2,i));
        legend(SNRstr)
        grid on;
subtitle('Linear, 440 Hz ')
subplot(4,1,3)
plot(linspace(0, Fs-1, Fs), X(:,3), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
        SNRstr = sprintf('SNR: %.1f',SNR(3,i));
        legend(SNRstr)
        grid on;
subtitle('Cubic Lagrange, 440 Hz')
subplot(4,1,4)
plot(linspace(0, Fs-1, Fs), X(:,4), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
        SNRstr = sprintf('SNR: %.1f',SNR(4,i));
        legend(SNRstr)
        grid on;
subtitle('Sinc, 440 Hz')



