clear; close all; clc;

%%

addpath('./helpers');

Fs = 44100;
duration = 4;
F0 = [27.5,440, 1046.5, 4081];
%F0 = [27.5, 4081];
Lt = 2048;


    fontName = 'Times';
    fontSize = 12;

% Specify wavetables, either...
% a single trivial wavetable:
% wavetables = "square";
% an array of trivial wavetables:
% wavetables = ["sawtooth", "noise", "square", "sine", "sineBroken"];
% an audio file to read and split into wavetable chunks.
 wavetables = audioread('./wavetables/braids2.wav');

%IntTypes = {'truncate','linear','cubic','sinc'};
Mipmaps = [1,3,6];
%%
for i=1:4
for n=1:1

testTable = wavetable(Fs, duration, F0(i), ...
    'Wavetables', wavetables, ...
    'WavetableLength', 2048, ...
    'InterpolationType', 'cubic', ...
    'Oversample',2 , ...
    'MipmapsPerOctave', 3, ...
    'OutputAmplitude', 1 ...
);


        SNR(n,i) = snr(testTable, Fs, round(Fs*n/2/F0(i))) 
        pitchEstimates(n,i) = mean(pitch(testTable, Fs, 'Range', [20, 5000], 'Method', 'LHS'));
        specCentroids(n,i) = mean(spectralCentroid(testTable,Fs))
        rmsValues(n,i) = rms(testTable);
end 
end

%%
for n=1:4


y(:,n) = wavetable(Fs, duration, F0(n), ...
    'Wavetables', wavetables, ...
    'WavetableLength', Lt, ...
    'InterpolationType', 'cubic', ...
    'Oversample', 2, ...
    'MipmapsPerOctave', 3, ...
    'OutputAmplitude', 1 ...
);

    X(:,n) = abs(fft(y(:,n), Fs));
   X(:,n) = db(X(:,n)/max(X(:,n)));

           %get values of test wavetables


end 

close all;
                chunkLength = 2^8;
                
                for n=1:floor(length(wavetables)/chunkLength)
                    sourceWavetables{n} = resample( ...
                        wavetables((n-1)*chunkLength + 1:n*chunkLength), ...
                        Lt, ...
                        chunkLength ...
                    );
                end

               
  N = length(sourceWavetables{1});
 % t = (1:N)/Fs;
figure('Position', [500, 100, 600, 800]);
set(gcf, 'Color', 'none');
subplot(5,1,1)
        plot( sourceWavetables{1}), ...
        grid on, ...
        xlabel('Sample Index'), ...
        ylabel('Amplitude'), ...
        ylim([-1.25, 1.25]), ...
        xlim([0, Lt]), ...
        set(gca,'fontsize',fontSize,'fontname',fontName);
        set(gcf, 'color', 'none');    
        subtitle('(a) Raw Wavetable In Time Domain')
      
subplot(5,1,2)
plot(linspace(0, Fs-1, Fs), X(:,1), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gcf, 'color', 'none');    
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
%        SNRstr = sprintf('SNR: %.1f',SNR(1,i));
%        legend(SNRstr)
        grid on;
subtitle('(b) Frequency Domain of Arbritary Wavetable at 27.5 Hz')
subplot(5,1,3)
plot(linspace(0, Fs-1, Fs), X(:,2), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gcf, 'color', 'none');    
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
%        SNRstr = sprintf('SNR: %.1f',SNR(2,i));
%        legend(SNRstr)
        grid on;
subtitle('(c) Frequency Domain of Arbritary Wavetable at 440 Hz ')
subplot(5,1,4)
plot(linspace(0, Fs-1, Fs), X(:,3), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
        set(gcf, 'color', 'none');    
%        SNRstr = sprintf('SNR: %.1f',SNR(3,i));
%        legend(SNRstr)
        grid on;
subtitle('(d) Frequency Domain of Arbritary Wavetable at 1046.5 Hz')
subplot(5,1,5)
plot(linspace(0, Fs-1, Fs), X(:,4), 'LineWidth', 1), ...
        axis([0 Fs/2 -100 5]), ...
        xlabel('Freq (kHz)'), ...
        ylabel('Magnitude (dB)'), ...
        % title('Spectrum'),...
        set(gca,'XTick',[0 5e3 10e3 15e3 20e3]), ...
        set(gca,'XTickLabel',[{'0'}, '5', '10' '15' '20']), ...
        set(gca,'YTick',-200:20:0), ...
        set(gca,'fontsize',fontSize,'fontname',fontName), ...
        set(gcf, 'color', 'none');    
 %       SNRstr = sprintf('SNR: %.1f',SNR(4,i));
%        legend(SNRstr)
        grid on;
subtitle('(e) Frequency Domain of Arbritary Wavetable at 4186 Hz')
export_fig arbritarywavetable2.png -m4
%%
figure 
subplot(311)
    spectrogram(y(:,1), 512, 64, 512, Fs, 'yaxis'), ...
    ylim([0, 22]);
    title('Mipmap: 1 per octave')
    subplot(312)
        spectrogram(y(:,2), 512, 64, 512, Fs, 'yaxis'), ...
    ylim([0, 22]);
        title('Mipmap: 3 per octave')
    subplot(313)
        spectrogram(y(:,3), 512, 64, 512, Fs, 'yaxis'), ...
    ylim([0, 22]);
        title('Mipmap: 6 per octave')